import localFont from "next/font/local";
import "./globals.css";

// Импортируем только Bold Sansation
const sansationBold = localFont({
  src: "./fonts/Sansation-Bold.ttf",
  variable: "--font-sansation-bold",
  weight: "700",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sansationBold.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
